server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: dev

  application:
    name: gateway-ms
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: localhost:8848

    gateway: # config the routes for gateway
      routes:
        - id: service-provider          #将/service-provider/开头的请求转发到service-provider
          uri: lb://service-provider
          predicates:
            - Path=/service-provider/**
          filters:
            - StripPrefix=1               #表明前缀/provider1需要截取掉nacos:

# 日志配置文件
logging:
  config: classpath:logback-spring.xml


